// ============================================================
//  songs.js  –  Tamil Emotion → Song Mapping
//  Large pool per emotion — 6 random songs picked each time.
// ============================================================

const SONG_MAP = {

  happy: [
    { title: "Aalaporan Thamizhan",    artist: "AR Rahman – Mersal",              mood: "upbeat" },
    { title: "Vaathi Coming",          artist: "Anirudh – Master",                mood: "upbeat" },
    { title: "Enjoy Enjaami",          artist: "Dhee ft. Arivu",                  mood: "upbeat" },
    { title: "Kannaana Kanney",        artist: "D. Imman – Viswasam",             mood: "upbeat" },
    { title: "Rowdy Baby",             artist: "Yuvan Shankar Raja – Maari 2",    mood: "upbeat" },
    { title: "Aaluma Doluma",          artist: "Anirudh – Vedalam",               mood: "upbeat" },
    { title: "Arabic Kuthu",           artist: "Anirudh – Beast",                 mood: "upbeat" },
    { title: "Chellamma",              artist: "Anirudh – Doctor",                mood: "upbeat" },
    { title: "Kutti Story",            artist: "Anirudh – Master",                mood: "upbeat" },
    { title: "Jolly O Gymkhana",       artist: "AR Rahman – Beast",               mood: "upbeat" },
    { title: "Macho",                  artist: "Anirudh – Sketch",                mood: "upbeat" },
    { title: "Selfie Pulla",           artist: "Anirudh – Kaththi",               mood: "upbeat" },
    { title: "Naana Thadedha",         artist: "Anirudh – Wunderbar",             mood: "upbeat" },
    { title: "One Two Three Four",     artist: "Anirudh – NOTA",                  mood: "upbeat" },
    { title: "Ottagatha Kattiko",      artist: "Anirudh – Velaikkaran",           mood: "upbeat" },
    { title: "Maari Thara Local",      artist: "Anirudh – Maari",                 mood: "upbeat" },
    { title: "Why This Kolaveri Di",   artist: "Anirudh – 3",                     mood: "upbeat" },
    { title: "Adada Adada",            artist: "GV Prakash – Moonu",              mood: "upbeat" },
    { title: "Machi Open the Bottle",  artist: "Yuvan – Mankatha",                mood: "upbeat" },
    { title: "Vera Maari",             artist: "Anirudh – Maari 2",               mood: "upbeat" },
    { title: "Inji Idupazhagi",        artist: "Anirudh – Kaththi",               mood: "upbeat" },
    { title: "Mersal Arasan",          artist: "AR Rahman – Mersal",              mood: "upbeat" },
    { title: "Bigil Bigil Bigila",     artist: "AR Rahman – Bigil",               mood: "upbeat" },
    { title: "Donu Donu Donu",         artist: "D. Imman – Ethir Neechal",        mood: "upbeat" },
    { title: "Surviva",                artist: "Anirudh – Vivegam",               mood: "upbeat" },
    { title: "Konjam Konjam",          artist: "Harris Jayaraj – Unnale Unnale",  mood: "upbeat" },
    { title: "Po Nee Po",              artist: "Harris Jayaraj – 3",              mood: "upbeat" },
    { title: "Simtaangaran",           artist: "AR Rahman – Sarkar",              mood: "upbeat" },
    { title: "Verithanam",             artist: "AR Rahman – Bigil",               mood: "upbeat" },
    { title: "Vaadi Vaadi",            artist: "Yuvan – Sachein",                 mood: "upbeat" },
  ],

  sad: [
    { title: "Ennodu Nee Irundhaal",   artist: "AR Rahman – I",                        mood: "melancholy" },
    { title: "Munbe Vaa",              artist: "AR Rahman – Sillunu Oru Kaadhal",      mood: "melancholy" },
    { title: "Nenjukkul Peidhidum",    artist: "Harris Jayaraj – Vaaranam Aayiram",   mood: "melancholy" },
    { title: "Idhayam Thirayadhe",     artist: "Yuvan Shankar Raja – Bheema",         mood: "melancholy" },
    { title: "Uyire",                  artist: "AR Rahman – Bombay",                  mood: "melancholy" },
    { title: "Kadhal Sadugudu",        artist: "AR Rahman – Alaipayuthe",             mood: "melancholy" },
    { title: "Vaseegara",              artist: "Harris Jayaraj – Minnale",            mood: "melancholy" },
    { title: "Yennai Maatrum Kadhale", artist: "Harris Jayaraj – Kaakha Kaakha",     mood: "melancholy" },
    { title: "Omana Penne",            artist: "AR Rahman – Kadhalar Dhinam",         mood: "melancholy" },
    { title: "Paartha Mudhal Naale",   artist: "Harris Jayaraj – Ghilli",             mood: "melancholy" },
    { title: "Thalli Pogathey",        artist: "AR Rahman – Achcham Yenbadhu Madamaiyada", mood: "melancholy" },
    { title: "Nee Paartha Vizhigal",   artist: "Harris Jayaraj – Anniyan",           mood: "melancholy" },
    { title: "Hosanna",                artist: "AR Rahman – Vinnaithaandi Varuvaayaa", mood: "melancholy" },
    { title: "Oru Murai Vanthu",       artist: "Ilaiyaraaja – Ninaithale Inikkum",   mood: "melancholy" },
    { title: "Kannamoochi Yenada",     artist: "AR Rahman – Kandukondain",            mood: "melancholy" },
    { title: "Adi Enna Enna",          artist: "Harris Jayaraj – Ko",                mood: "melancholy" },
    { title: "Mazhai Kuruvi",          artist: "AR Rahman – Chekka Chivantha Vaanam", mood: "melancholy" },
    { title: "Nenjame Nenjame",        artist: "AR Rahman – Rhythm",                 mood: "melancholy" },
    { title: "Enna Solla Pogirai",     artist: "Harris Jayaraj – Kandein Kadhalai",  mood: "melancholy" },
    { title: "Nila Kaaigirathu",       artist: "Ilaiyaraaja – Ninaithale Inikkum",   mood: "melancholy" },
    { title: "Ilamai Idho Idho",       artist: "Ilaiyaraaja – Ninaithale Inikkum",   mood: "melancholy" },
    { title: "Vaan Megam",             artist: "MS Viswanathan",                     mood: "melancholy" },
    { title: "Azhagiya Laila",         artist: "Harris Jayaraj – Vettaiyaadu",       mood: "melancholy" },
    { title: "Oru Deivam Thantha",     artist: "Vidyasagar – Kaakha Kaakha",         mood: "melancholy" },
    { title: "Pookal Pookum",          artist: "Ilaiyaraaja – Ninaithale Inikkum",   mood: "melancholy" },
    { title: "Un Mela Aasadhan",       artist: "Yuvan – Sillunu Oru Kaadhal",        mood: "melancholy" },
    { title: "Kadhal Cricket",         artist: "GV Prakash – Deiva Thirumagal",      mood: "melancholy" },
    { title: "Enge Enathu Kavithai",   artist: "Ilaiyaraaja – Mouna Ragam",          mood: "melancholy" },
    { title: "Aayiram Jenmangal",      artist: "Ilaiyaraaja – Mouna Ragam",          mood: "melancholy" },
    { title: "Kannodu Kaanbadhellam",  artist: "AR Rahman – Jeans",                  mood: "melancholy" },
  ],

  angry: [
    { title: "Verithanam",             artist: "AR Rahman – Bigil",                  mood: "aggressive" },
    { title: "Beast Mode",             artist: "Anirudh – Beast",                    mood: "aggressive" },
    { title: "Simtaangaran",           artist: "AR Rahman – Sarkar",                 mood: "aggressive" },
    { title: "Oru Viral Puratchi",     artist: "GV Prakash – Puratchi Thalaivar",    mood: "aggressive" },
    { title: "Karuppan",               artist: "D. Imman – Thaanaa Serndha Koottam", mood: "aggressive" },
    { title: "Kutti Story",            artist: "Anirudh – Master",                   mood: "aggressive" },
    { title: "Aalaporan Thamizhan",    artist: "AR Rahman – Mersal",                 mood: "aggressive" },
    { title: "Vaathi Coming",          artist: "Anirudh – Master",                   mood: "aggressive" },
    { title: "Naan Avan Illai",        artist: "Yuvan Shankar Raja",                 mood: "aggressive" },
    { title: "Bigil Bigil Bigila",     artist: "AR Rahman – Bigil",                  mood: "aggressive" },
    { title: "Surviva",                artist: "Anirudh – Vivegam",                  mood: "aggressive" },
    { title: "Villangam Illatha",      artist: "GV Prakash – Ennai Noki Paayum",     mood: "aggressive" },
    { title: "Marana Mass",            artist: "Anirudh – Petta",                    mood: "aggressive" },
    { title: "Dont Dont",              artist: "Anirudh – Petta",                    mood: "aggressive" },
    { title: "Kalam Kalam",            artist: "Anirudh – Vada Chennai",             mood: "aggressive" },
    { title: "Anbe Sivam Theme",       artist: "Vidyasagar – Anbe Sivam",            mood: "aggressive" },
    { title: "Kadhal Virus",           artist: "GV Prakash – Enakkul Oruvan",        mood: "aggressive" },
    { title: "Sollividava",            artist: "Anirudh – Kabali",                   mood: "aggressive" },
    { title: "Neruppu Da",             artist: "Anirudh – Rajinimurugan",            mood: "aggressive" },
    { title: "Iravukku Aayiram Kangal",artist: "D. Imman",                           mood: "aggressive" },
  ],

  neutral: [
    { title: "Vennilave Vennilave",    artist: "AR Rahman – Minsara Kanavu",         mood: "chill" },
    { title: "Hosanna",                artist: "AR Rahman – Vinnaithaandi Varuvaayaa", mood: "chill" },
    { title: "Ilamai Idho Idho",       artist: "Ilaiyaraaja – Ninaithale Inikkum",   mood: "chill" },
    { title: "Kannodu Kaanbadhellam",  artist: "AR Rahman – Jeans",                  mood: "chill" },
    { title: "Yennai Maatrum Kadhale", artist: "Harris Jayaraj – Kaakha Kaakha",    mood: "chill" },
    { title: "Oru Murai Vanthu",       artist: "Ilaiyaraaja",                        mood: "chill" },
    { title: "Mazhai",                 artist: "Harris Jayaraj – Mazhai",            mood: "chill" },
    { title: "Vaseegara",              artist: "Harris Jayaraj – Minnale",           mood: "chill" },
    { title: "Nila Kaaigirathu",       artist: "Ilaiyaraaja",                        mood: "chill" },
    { title: "Kannamoochi Yenada",     artist: "AR Rahman – Kandukondain",           mood: "chill" },
    { title: "Nee Paartha Vizhigal",   artist: "Harris Jayaraj – Anniyan",           mood: "chill" },
    { title: "Adiye Kolluthe",         artist: "Harris Jayaraj – Vaaranam Aayiram",  mood: "chill" },
    { title: "Oh Manapenne",           artist: "AR Rahman – Minnale",                mood: "chill" },
    { title: "Nenjukulle",             artist: "AR Rahman – Kadal",                  mood: "chill" },
    { title: "Un Mela Aasadhan",       artist: "Yuvan – Sillunu Oru Kaadhal",        mood: "chill" },
    { title: "Pookal Pookum",          artist: "Ilaiyaraaja",                        mood: "chill" },
    { title: "Ennodu Nee Irundhaal",   artist: "AR Rahman – I",                      mood: "chill" },
    { title: "Munbe Vaa",              artist: "AR Rahman – Sillunu Oru Kaadhal",    mood: "chill" },
    { title: "Uyire Uyire",            artist: "AR Rahman – Bombay",                 mood: "chill" },
    { title: "Nila Adhu Vasantham",    artist: "Ilaiyaraaja",                        mood: "chill" },
    { title: "Oru Deivam Thantha",     artist: "Vidyasagar – Kaakha Kaakha",         mood: "chill" },
    { title: "Ennavale Adi Ennavale",  artist: "AR Rahman – Kadhalar Dhinam",        mood: "chill" },
    { title: "Kadhal Cricket",         artist: "GV Prakash – Deiva Thirumagal",      mood: "chill" },
    { title: "En Iniya Pon Nilave",    artist: "Ilaiyaraaja",                        mood: "chill" },
    { title: "Mazhai Kuruvi",          artist: "AR Rahman – Chekka Chivantha Vaanam", mood: "chill" },
  ],

  surprised: [
    { title: "Chellamma",              artist: "Anirudh – Doctor",                   mood: "electric" },
    { title: "Dance Move",             artist: "GV Prakash – Darling",               mood: "electric" },
    { title: "Ottagatha Kattiko",      artist: "Anirudh – Velaikkaran",              mood: "electric" },
    { title: "Selfie Pulla",           artist: "Anirudh – Kaththi",                  mood: "electric" },
    { title: "Maari Thara Local",      artist: "Anirudh – Maari",                    mood: "electric" },
    { title: "Macho",                  artist: "Anirudh – Sketch",                   mood: "electric" },
    { title: "Po Nee Po",              artist: "Harris Jayaraj – 3",                 mood: "electric" },
    { title: "Why This Kolaveri Di",   artist: "Anirudh – 3",                        mood: "electric" },
    { title: "Vera Maari",             artist: "Anirudh – Maari 2",                  mood: "electric" },
    { title: "Adada Adada",            artist: "GV Prakash – Moonu",                 mood: "electric" },
    { title: "Inji Idupazhagi",        artist: "Anirudh – Kaththi",                  mood: "electric" },
    { title: "Jolly O Gymkhana",       artist: "AR Rahman – Beast",                  mood: "electric" },
    { title: "One Two Three Four",     artist: "Anirudh – NOTA",                     mood: "electric" },
    { title: "Naana Thadedha",         artist: "Anirudh – Wunderbar",                mood: "electric" },
    { title: "Vaadi Vaadi",            artist: "Yuvan – Sachein",                    mood: "electric" },
    { title: "Machi Open the Bottle",  artist: "Yuvan – Mankatha",                   mood: "electric" },
    { title: "Neruppu Da",             artist: "Anirudh – Rajinimurugan",            mood: "electric" },
    { title: "Donu Donu Donu",         artist: "D. Imman – Ethir Neechal",           mood: "electric" },
    { title: "Konjam Konjam",          artist: "Harris Jayaraj – Unnale Unnale",     mood: "electric" },
    { title: "Marana Mass",            artist: "Anirudh – Petta",                    mood: "electric" },
  ],

  fearful: [
    { title: "Aayiram Jenmangal",      artist: "Ilaiyaraaja – Mouna Ragam",          mood: "haunting" },
    { title: "Vaan Megam",             artist: "MS Viswanathan",                     mood: "haunting" },
    { title: "Nenjame Nenjame",        artist: "AR Rahman – Rhythm",                 mood: "haunting" },
    { title: "En Iniya Pon Nilave",    artist: "Ilaiyaraaja",                        mood: "haunting" },
    { title: "Omana Penne",            artist: "AR Rahman – Kadhalar Dhinam",        mood: "haunting" },
    { title: "Enge Enathu Kavithai",   artist: "Ilaiyaraaja – Mouna Ragam",          mood: "haunting" },
    { title: "Nila Adhu Vasantham",    artist: "Ilaiyaraaja",                        mood: "haunting" },
    { title: "Pookal Pookum",          artist: "Ilaiyaraaja",                        mood: "haunting" },
    { title: "Mazhai",                 artist: "Harris Jayaraj – Mazhai",            mood: "haunting" },
    { title: "Oru Deivam Thantha",     artist: "Vidyasagar – Kaakha Kaakha",         mood: "haunting" },
    { title: "Nila Kaaigirathu",       artist: "Ilaiyaraaja",                        mood: "haunting" },
    { title: "Kanne Kalaimaane",       artist: "AR Rahman – 96",                     mood: "haunting" },
    { title: "Kaadhal Rojave",         artist: "AR Rahman – Roja",                   mood: "haunting" },
    { title: "Kadhal Oviyam",          artist: "Ilaiyaraaja – Alaigal Oivathillai",  mood: "haunting" },
    { title: "Panivizhum Malarvanam",  artist: "Ilaiyaraaja – Ninaithale Inikkum",   mood: "haunting" },
  ],

  disgusted: [
    { title: "Sollividava",            artist: "Anirudh – Kabali",                   mood: "dark" },
    { title: "Karuppan",               artist: "D. Imman – Thaanaa Serndha Koottam", mood: "dark" },
    { title: "Naan Avan Illai",        artist: "Yuvan Shankar Raja",                 mood: "dark" },
    { title: "Kadhal Azhivathillai",   artist: "Harris Jayaraj – Vettaiyaadu",      mood: "dark" },
    { title: "Thalli Pogathey",        artist: "AR Rahman – Achcham Yenbadhu Madamaiyada", mood: "dark" },
    { title: "Iruvar Ullam",           artist: "AR Rahman – Iruvar",                mood: "dark" },
    { title: "Kalam Kalam",            artist: "Anirudh – Vada Chennai",             mood: "dark" },
    { title: "Villangam Illatha",      artist: "GV Prakash",                         mood: "dark" },
    { title: "Nenjukulle",             artist: "AR Rahman – Kadal",                  mood: "dark" },
    { title: "Iravukku Aayiram Kangal",artist: "D. Imman",                           mood: "dark" },
    { title: "Kadhal Virus",           artist: "GV Prakash – Enakkul Oruvan",        mood: "dark" },
    { title: "Anbe Sivam Theme",       artist: "Vidyasagar – Anbe Sivam",            mood: "dark" },
    { title: "Nee Paartha Vizhigal",   artist: "Harris Jayaraj – Anniyan",           mood: "dark" },
    { title: "Kaadhal Rojave",         artist: "AR Rahman – Roja",                   mood: "dark" },
    { title: "Mazhai Kuruvi",          artist: "AR Rahman – Chekka Chivantha Vaanam", mood: "dark" },
  ],

};

// ── Pick 6 random songs from a pool (no repeats) ────────────
function getRandomSongs(emotion, count = 6) {
  const pool = SONG_MAP[emotion] || SONG_MAP.neutral;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

// Emoji & colour labels per emotion
const EMOTION_META = {
  happy:     { emoji: "😄", label: "Happy",     color: "#FFD93D" },
  sad:       { emoji: "😢", label: "Sad",       color: "#74B9FF" },
  angry:     { emoji: "😠", label: "Angry",     color: "#FF6B6B" },
  neutral:   { emoji: "😐", label: "Neutral",   color: "#A29BFE" },
  surprised: { emoji: "😲", label: "Surprised", color: "#FD79A8" },
  fearful:   { emoji: "😨", label: "Fearful",   color: "#81ECEC" },
  disgusted: { emoji: "🤢", label: "Disgusted", color: "#55EFC4" },
};
